spring.application.name=rugato
spring.datasource.url =jdbc:mysql://mydatabase.cj8qkoiwq43t.us-east-2.rds.amazonaws.com:3306/rugato?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Mexico_City
spring.datasource.username =facuadmin
spring.datasource.password =mySuP3RSeCR3tPass*_*
server.port=8082